import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Saigonexpress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Image
          src="/logo.jpg"
          alt="saigonexpress logo"
          width={140}
          height={50}
        />
        <nav>
          <a href="#">Hjem</a>
          <a href="#omoss">Om oss</a>
          <a href="#meny">Meny</a>
          <a href="#galleri">Galleri</a>
          <a href="#kontaktoss">Kontakt oss</a>
        </nav>
        <div>
          <a href="#">Theme</a>
          <a href="#">Facebook</a>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.splash}>
          <div className={styles.splashWrapper}>
            <div className={styles.titleWrapper}>
              <h1 className={styles.title}>Velkommen til Saigon Express</h1>
              <p>
                Nå er det levering hos oss via <span>Wolt</span> og{" "}
                <span>Just-eat!</span>
              </p>
            </div>
            <div className={styles.buttonWrapper}>
              <button>Bestill Wolt</button>
              <button>Bestill Just-eat</button>
              <br />
              <button>Bestill Takeaway</button>
            </div>
          </div>
          <div className={styles.languagePicker}>
            <select name="" id="">
              <option value="">Select Language...</option>
            </select>
          </div>
          <div className={styles.imageScroller}>
            <button className={styles.active}></button>
            <button></button>
            <button></button>
            <button></button>
          </div>
        </div>
        <div id="omoss" className={styles.aboutus}>
          <h1>Om Saigon Express</h1>
          <p>
            Hos Saigon Express finner du velkjente Sørøst-Asiatiske retter fra
            det vietnamesiske, japanske, thailandske, kinesiske kjøkkenet. Alle
            retter serveres med tilhørende sauser eller dipper, som hver og en
            sørger for spennende preg på måltidene.
          </p>
          <p>
            Vi legger stor vekt på rask levering, retter lages etter
            bestillingen, samtidig som vi sørger for at maten alltid er frisk og
            velsmakende. Vi presenterer en sunn versjon av fastfood som du kan
            nyte i våre lokaler, eller ta med hjem som take away.
          </p>
          <p>Hjertelig velkommen til oss!</p>
        </div>
        <div id="meny" className={styles.menu}>
          <h1>Vår takeaway meny</h1>
          <p>
            <a href="">Ring og bestill</a> nå eller i forveien!
          </p>
          <div className={styles.menuDisplay}></div>
          <div>
            <p>... eller se menyen i eget vindu</p>
            <div>
              <button>Takeaway PDF meny</button>
              <button>Fullstendig PDF meny</button>
            </div>
          </div>
        </div>
        <div className={styles.parallaxSection}></div>
        <div id="galleri" className={styles.gallery}>
          <h1>Galleri</h1>
          <div className={styles.galleryWrapper}>
            <div className={styles.galleryDisplay}></div>
            <div className={styles.galleryDisplay}></div>
          </div>
        </div>
        <div id="kontaktoss" className={styles.contactus}>
          <div className={styles.infoWrapper}>
            <div className={styles.info}>
              <a href="#">Icon</a>
              <h3>Besøk oss</h3>
              <p>Maridalsveien 157, 0465 Oslo</p>
            </div>
            <div className={styles.info}>
              <a href="#">Icon</a>
              <h3>Kontakt oss</h3>
              <p>tlf: 222 30 900</p>
              <p>e-post: epost@saigonexpress.no</p>
            </div>
            <div className={styles.info}>
              <a href="#">Icon</a>
              <h3>Åpningstider</h3>
              <p>Text</p>
            </div>
            <div className={styles.info}>TripAdvisor</div>
          </div>
          <div className={styles.parallaxSection}></div>
        </div>
        <div className={styles.map}></div>
      </main>

      <footer className={styles.footer}>
        <p>
          Copyright © 2021 - Alle rettigheter forbeholdt av Saigon Express
          SAGENE.
        </p>
        <p>Nettside designet av Joiedesign</p>
        <div>
          Page top
          <a href="#">
            <button></button>
          </a>
        </div>
      </footer>
    </div>
  );
};
export default Home;
